import { beforeEach, describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { strFromU8, unzipSync } from "fflate";
import { evaluateReadiness } from "../../../domain/readiness";
import { ProjectModelSchema } from "../../../domain/model";
import type { ResolvedRedactionPolicy } from "../../../ai/redaction";
import { getWholeProjectPromptFile } from "../../../ai/prompts/wholeProjectLibrary";
import { completeStructured } from "../../../ai/structuredIpc";
import { getA3RendererMap } from "../../../methods/registry";
import { buildMockAuditContext, proposeMockAuditFindings } from "./mockAudit";

/**
 * Faz 10/K2/D-213: the "flags a weak root cause on a deliberately-bad
 * project" half of Faz 10's own acceptance scenario. D-62's fixture corpus
 * gained a fifth kind, `deliberately-bad.ppsx` (generated by
 * `gen_ppsx_fixtures.rs`, never hand-written — same discipline as the
 * original four), a project every S1-S8 mechanical gate reads as clean but
 * which carries three real narrative breaks. This PROBE test chains that
 * *real* fixture — read through the same `fflate` unzip
 * `fixtures.test.ts` already established, not a hand-typed stand-in —
 * through `buildMockAuditContext` and `proposeMockAuditFindings` against a
 * *faked* LlmProvider response (this environment has no real Tauri/Vorion
 * round-trip, the same honestly-owed gap as D-105/D-113/D-136/D-200/D-201/
 * D-204/D-213/D-214's own real-webview walkthroughs).
 */

const FIXTURES_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..", "fixtures", "ppsx");

function loadDeliberatelyBadProject() {
  const bytes = readFileSync(join(FIXTURES_DIR, "deliberately-bad.ppsx"));
  const files = unzipSync(new Uint8Array(bytes));
  const projectJsonBytes = files["project.json"];
  if (!projectJsonBytes) {
    throw new Error("deliberately-bad.ppsx: archive has no project.json");
  }
  return ProjectModelSchema.parse(JSON.parse(strFromU8(projectJsonBytes)));
}

vi.mock("../../../ai/structuredIpc", () => ({
  completeStructured: vi.fn(),
}));

const mockCompleteStructured = vi.mocked(completeStructured);

const OFF: ResolvedRedactionPolicy = { mode: "off", terms: [], preserveNumbers: true };

beforeEach(() => {
  mockCompleteStructured.mockReset();
});

describe("Faz 10 acceptance scenario: flags a weak root cause on a deliberately-bad project", () => {
  it("evaluateReadiness reports every S1-S8 gate as passing — the mechanical checks see nothing wrong", () => {
    const project = loadDeliberatelyBadProject();
    const readiness = evaluateReadiness(project);

    for (const stepId of [1, 2, 3, 4, 5] as const) {
      expect(readiness[stepId].status).toBe("ok");
    }
    // Steps 6 and 7 are empty — D-196's "empty step never flags" rule.
    expect(readiness[6].status).toBe("ok");
    expect(readiness[7].status).toBe("ok");
    expect(readiness[8].status).toBe("ok");
  });

  it("chains the real fixture through buildMockAuditContext and a faked LlmProvider response, landing on a finding that names the person-blamed root cause", async () => {
    const project = loadDeliberatelyBadProject();
    const promptFile = getWholeProjectPromptFile("mock-audit", "v1");
    if (!promptFile) {
      throw new Error("mock-audit prompt file must be registered for this probe to run");
    }

    const { contextText } = buildMockAuditContext(project, getA3RendererMap());
    expect(contextText).toContain("Operatör dikkatsizliği");
    expect(contextText).toContain("Step 4");
    expect(contextText).toContain("Step 8");

    // Stands in for the real Vorion response this environment cannot make —
    // a plausible auditor reaction to the real context text built above.
    mockCompleteStructured.mockResolvedValueOnce({
      findings: [
        {
          stepId: 4,
          severity: "major",
          category: "person-blamed-root-cause",
          message:
            "The confirmed root cause 'Operatör dikkatsizliği' blames an individual rather than identifying the systemic factor behind it.",
        },
        {
          stepId: 8,
          severity: "major",
          category: "unimplemented-standardization",
          message: "The control plan is marked complete, but Step 6 records no action that implemented this change.",
        },
      ],
    });

    const result = await proposeMockAuditFindings({
      promptBody: promptFile.body,
      contextText,
      modelId: "vorion/gpt-4o",
      redaction: OFF,
    });

    expect(result.outcome).toBe("success");
    if (result.outcome !== "success") {
      throw new Error("expected the mock-audit proposal to succeed");
    }
    expect(result.findings).toHaveLength(2);
    expect(result.findings.some((f) => f.category === "person-blamed-root-cause" && f.stepId === 4)).toBe(true);
    expect(result.findings.some((f) => f.category === "unimplemented-standardization" && f.stepId === 8)).toBe(true);

    const promptSent = mockCompleteStructured.mock.calls[0]?.[0] as string;
    expect(promptSent).toContain("Operatör dikkatsizliği");
  });
});
