//! D-62: the checked-in `.ppsx` fixture corpus (generated by
//! `src/bin/gen_ppsx_fixtures.rs`, never by this test) must keep opening
//! cleanly through the real container reader. This is the container-level
//! half of the guarantee; `src/domain/migrations/__tests__/fixtures.test.ts`
//! covers the `ProjectModel` shape half on the TS/Zod side.

use pps_hachi_lib::ppsx::read_ppsx;
use std::path::PathBuf;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("src-tauri has a parent directory")
        .join("fixtures")
        .join("ppsx")
}

fn fixture_names() -> Vec<&'static str> {
    vec![
        "minimal.ppsx",
        "fully-populated.ppsx",
        "turkish-text.ppsx",
        "unknown-method.ppsx",
        "deliberately-bad.ppsx",
    ]
}

#[test]
fn every_checked_in_fixture_opens_through_the_real_reader() {
    let dir = fixtures_dir();
    for name in fixture_names() {
        let path = dir.join(name);
        let contents = read_ppsx(&path).unwrap_or_else(|e| panic!("{name} failed to open: {e}"));
        assert!(
            contents.manifest.get("id").is_some(),
            "{name}: manifest missing id"
        );
        assert_eq!(
            contents.manifest["id"], contents.project["id"],
            "{name}: manifest/project id mismatch"
        );
    }
}

#[test]
fn fixture_corpus_has_not_shrunk() {
    // A minimal guard against someone quietly deleting a fixture instead of
    // regenerating the corpus: the exact set of 5 kinds (D-62's original 4 —
    // minimal, fully-populated, Turkish text, unknown methodId — plus
    // Faz 10/K2/D-213's "deliberately-bad" fixture for the mock-auditor
    // acceptance scenario).
    let dir = fixtures_dir();
    let count = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("fixtures/ppsx unreadable: {e}"))
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "ppsx"))
        .count();
    assert_eq!(
        count,
        fixture_names().len(),
        "expected exactly the 5 fixture kinds"
    );
}
